Blood: Add crouch toggle
nukeykt/NBlood pull request #783
Opened 2024-02-17 23:23 UTC by tmyqlfpir

This PR adds crouch toggle functionality, and resolves issue #781

2024-02-18 05:00 UTC, Hendricks266 commented
Instead of a modifier on the behavior of the crouch key, I would prefer Crouch and Toggle Crouch be separate and coexisting gamefuncs like how I implemented it in EDuke32.

2024-02-23 23:43 UTC, nukeykt requested changes

2024-02-23 23:43 UTC, nukeykt commented on source/duke3d/src/menus.cpp
> +static MenuRangeFloat_t MEO_MOUSESETUP_XSENSITIVITY = MAKE_MENURANGE( &CONTROL_MouseAxesSensitivity[0], &MF_Redfont, 0.f, 50.f, 50.f, 99, DisplayTypeInteger|EnforceIntervals );
position count should be adjusted to 101

2024-02-23 23:43 UTC, nukeykt commented on source/rr/src/menus.cpp
> +static MenuRangeFloat_t MEO_MOUSESETUP_XSENSITIVITY = MAKE_MENURANGE( &CONTROL_MouseAxesSensitivity[0], &MF_Redfont, 0.f, 10.f, 10.f, 91, DisplayTypeInteger|EnforceIntervals );
same

2024-02-23 23:43 UTC, nukeykt commented on source/rr/src/menus.cpp
> +static MenuRangeFloat_t MEO_MOUSESETUP_YSENSITIVITY = MAKE_MENURANGE( &CONTROL_MouseAxesSensitivity[1], &MF_Redfont, 0.f, 10.f, 10.f, 91, DisplayTypeInteger|EnforceIntervals );
here too

2024-02-24 04:25 UTC, nukeykt approved these changes

2024-02-24 04:31 UTC, merged